from datetime import datetime
from typing import Any

from sqlalchemy import (
    CHAR,
    Boolean,
    CheckConstraint,
    DateTime,
    Index,
    Integer,
    SmallInteger,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.core.ontology import ONTOLOGY_VERSION
from app.db.base import Base, in_check, not_zero_vector
from app.models._columns import created_at, ontology_vector, updated_at
from app.models.enums import DishVectorStatus


class DishVector(Base):
    """12-dimension vector of a dish, generated by the LLM from its name and description."""

    __tablename__ = "dish_vectors"
    __table_args__ = (
        CheckConstraint(in_check("status", DishVectorStatus), name="status"),
        CheckConstraint(not_zero_vector("vec"), name="vec_not_zero"),
        CheckConstraint(
            f"status <> '{DishVectorStatus.READY}' OR vec IS NOT NULL", name="ready_has_vec"
        ),
        CheckConstraint("attempt_count >= 0", name="attempt_count"),
        # Rows the background loop retries every 5 minutes.
        Index(
            "ix_dish_vectors_not_ready",
            "status",
            postgresql_where=text(f"status <> '{DishVectorStatus.READY}'"),
        ),
    )

    # = core.dishes.id (soft reference, no FK across schemas)
    dish_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    vec: Mapped[list[float] | None] = mapped_column(ontology_vector())
    raw_ai_output: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    source_hash: Mapped[str] = mapped_column(CHAR(64))
    model_name: Mapped[str | None] = mapped_column(String(100))
    ontology_version: Mapped[int] = mapped_column(
        SmallInteger, server_default=text(str(ONTOLOGY_VERSION))
    )
    status: Mapped[str] = mapped_column(
        String(10), server_default=text(f"'{DishVectorStatus.PENDING}'")
    )
    attempt_count: Mapped[int] = mapped_column(SmallInteger, server_default=text("0"))
    last_error: Mapped[str | None] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, server_default=text("true"))
    name: Mapped[str | None] = mapped_column(String(200))
    description: Mapped[str | None] = mapped_column(Text)
    # occurred_at of the latest applied event; older events are stale.
    last_event_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()


class DishStats(Base):
    """Community likes/dislikes for the Wilson score (one vote per user, latest feedback)."""

    __tablename__ = "dish_stats"
    __table_args__ = (CheckConstraint("like_count >= 0 AND dislike_count >= 0", name="counts"),)

    dish_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    like_count: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    dislike_count: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    updated_at: Mapped[datetime] = updated_at()
